# Generated by Django 2.2.6 on 2019-10-14 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('number', models.IntegerField(unique=True, verbose_name='Порядковый номер')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('importance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDoApp.Importance', verbose_name='Важность')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 12, 43, 37, 859359, tzinfo=utc), verbose_name='Время конца')),
                ('check', models.BooleanField(default=False, verbose_name='Статус завершения')),
                ('importance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDoApp.Importance', verbose_name='Важность')),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoApp.ToDoList', verbose_name='Список')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('importance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToDoApp.Importance', verbose_name='Важность')),
            ],
        ),
    ]
